# Generated by Django 4.2.8 on 2026-05-23 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])])),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10)),
                ('file_size', models.IntegerField()),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('work_experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsing_error', models.TextField(blank=True, null=True)),
                ('parsing_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Parsed Resume',
                'verbose_name_plural': 'Parsed Resumes',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file', models.FileField(upload_to='resume_versions/%Y/%m/%d/')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Resume Version',
                'verbose_name_plural': 'Resume Versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['resume', '-version_number'], name='resumes_res_resume__38af84_idx')],
                'unique_together': {('resume', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-created_at'], name='resumes_res_user_id_6019d7_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_current'], name='resumes_res_is_curr_a82ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedresume',
            index=models.Index(fields=['parsing_status'], name='resumes_par_parsing_bb7999_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedresume',
            index=models.Index(fields=['-created_at'], name='resumes_par_created_78f147_idx'),
        ),
    ]
