# Generated by Django 4.2.8 on 2026-05-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('keyword_match_score', models.FloatField(default=0.0)),
                ('skills_match_score', models.FloatField(default=0.0)),
                ('resume_structure_score', models.FloatField(default=0.0)),
                ('experience_match_score', models.FloatField(default=0.0)),
                ('grammar_quality_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='moderate', max_length=20)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('formatting_issues_data', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'ATS Analysis',
                'verbose_name_plural': 'ATS Analyses',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('transferable_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analysis', to='analysis.atsanalysis')),
            ],
            options={
                'verbose_name': 'Skill Gap Analysis',
                'verbose_name_plural': 'Skill Gap Analyses',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('keyword', 'Keyword Addition'), ('skill', 'Skill Addition'), ('formatting', 'Formatting'), ('content', 'Content Restructuring'), ('action_verb', 'Action Verb'), ('experience', 'Experience Level')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('estimated_score_improvement', models.FloatField(default=0.0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.atsanalysis')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-priority', '-estimated_score_improvement'],
            },
        ),
        migrations.CreateModel(
            name='FormattingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('suggested_fix', models.TextField()),
                ('impact_on_parsing', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatting_issues', to='analysis.atsanalysis')),
            ],
            options={
                'verbose_name': 'Formatting Issue',
                'verbose_name_plural': 'Formatting Issues',
            },
        ),
    ]
